# Introduction

This notebook reports the Pearson correlation between each variable and the target outcome. While these correlations cannot tell us exactly which variables will offer the best performance in the context of a holistic productionized model, they're a good starting point for dimensionality reduction.

In [9]:
import numpy as np
import pandas as pd
import scipy.stats

from utils import bad_rate_by_category

pd.set_option('display.max_rows', 200)
pd.set_option('display.max_columns', 50)

## Data

In [10]:
# Import data and data dictionary
data = pd.read_pickle('output_data/01_data.pkl')

data_dict = pd.read_pickle('output_data/01_data_dict.pkl')

## Potential Features

In [11]:
# Designate eda categories as containing features
prelim_feature_dict = ['credit_score', 'personal_finance', 'other_info']
data_dict['potential_feature'] = data_dict.apply(lambda x: x.eda_category in prelim_feature_dict, axis=1)

## Pearson Correlations

In [12]:
# Function to evaluate pearson correlation
def correlate_pearson(var1, var2, data):
    # Drop rows without either input or output variable
    data_notna = data.dropna(axis=0, subset=[var1, var2])
    
    # Run Pearson correlation
    pearson, pearson_p = scipy.stats.pearsonr(data_notna[var1], data_notna[var2])
    
    return pearson, pearson_p

In [13]:
# Designate list of potential model features
potential_features = data_dict.loc[data_dict['potential_feature']==True, 'variable'].values

# For each potential feature, calculate Pearson's correlation 
# and its p-value and store them in the data dictionary
for var in potential_features:
    pearson, pearson_p = correlate_pearson(var, 'bad', data)
    data_dict.loc[data_dict['variable']==var,'pearson'] = pearson
    data_dict.loc[data_dict['variable']==var,'pearson_p'] = pearson_p

In [15]:
data_dict.sort_values('pearson_p').reset_index(drop=True)

,variable,var_dtype,eda_category,categorical,coverage,potential_feature,pearson,pearson_p
0,raw_FICO_retail,int64,credit_score,0,1.000000,True,-0.180558,0.000004
1,payment_frequency_bi_weekly,uint8,personal_finance,-1,1.000000,True,0.177818,0.000005
2,payment_frequency_per_month,int64,personal_finance,0,1.000000,True,0.160181,0.000041
3,raw_FICO_telecom,int64,credit_score,0,1.000000,True,-0.156673,0.000060
4,raw_FICO_bank_card,int64,credit_score,0,1.000000,True,-0.152722,0.000093
5,raw_FICO_money,int64,credit_score,0,1.000000,True,-0.152437,0.000096
6,payment_frequency_monthly,uint8,personal_finance,-1,1.000000,True,-0.136097,0.000503
7,payment_frequency_semi_monthly,uint8,personal_finance,-1,1.000000,True,-0.129028,0.000977
8,payment_frequency_weekly,uint8,personal_finance,-1,1.000000,True,0.103345,0.008370
9,bank_account_duration_months,float64,other_info,0,0.998462,True,-0.102491,0.008926
10,bank_account_duration_6_months_or_less,uint8,personal_finance,-1,1.000000,True,0.102211,0.009115
11,bank_account_duration_3+_years,uint8,personal_finance,-1,1.000000,True,-0.096812,0.013538
12,how_use_money_pay_off_loans_overdrawn_acct,uint8,personal_finance,-1,1.000000,True,-0.095151,0.015236
13,expense_type_credit,uint8,personal_finance,-1,1.000000,True,-0.095151,0.015236
14,application_month_of_cycle,int64,other_info,0,1.000000,True,-0.086858,0.026804
15,how_use_money_gifts_leisure,uint8,personal_finance,-1,1.000000,True,-0.074237,0.058540
16,home_phone_type_home,uint8,other_info,-1,1.000000,True,-0.072168,0.065947
17,residence_duration_7_12_months,uint8,other_info,-1,1.000000,True,0.071946,0.066787
18,how_use_money_bills,uint8,personal_finance,-1,1.000000,True,0.066545,0.090041
19,home_phone_type_mobile,uint8,other_info,-1,1.000000,True,0.065296,0.096251
20,residence_duration_3+_years,uint8,other_info,-1,1.000000,True,-0.064986,0.097846
21,residence_duration_months,float64,other_info,0,1.000000,True,-0.063044,0.108316
22,bank_id_0297,uint8,personal_finance,-1,1.000000,True,0.060603,0.122701
23,bank_id_0154,uint8,personal_finance,-1,1.000000,True,-0.060042,0.126211
24,how_use_money_bills_general,uint8,personal_finance,-1,1.000000,True,-0.056442,0.150612
25,bank_id_0215,uint8,personal_finance,-1,1.000000,True,-0.055170,0.160041
26,other_phone_type_work,uint8,other_info,-1,1.000000,True,0.054079,0.168479
27,bank_id_7751,uint8,personal_finance,-1,1.000000,True,-0.053980,0.169265
28,how_use_money_rent_mortgage,uint8,personal_finance,-1,1.000000,True,-0.046296,0.238525
29,bank_id_9999,uint8,personal_finance,-1,1.000000,True,0.041082,0.295642
30,bank_account_duration_1_2_years,uint8,personal_finance,-1,1.000000,True,0.040795,0.299038
31,other_phone_type_mobile,uint8,other_info,-1,1.000000,True,0.038723,0.324267
32,how_use_money_other,uint8,personal_finance,-1,1.000000,True,0.036982,0.346523
33,how_use_money_won't_say,uint8,personal_finance,-1,1.000000,True,0.036005,0.359408
34,how_use_money_medical,uint8,personal_finance,-1,1.000000,True,-0.035903,0.360782
35,expense_type_general,uint8,personal_finance,-1,1.000000,True,0.035075,0.371961
36,monthly_rent_amount,int64,personal_finance,0,1.000000,True,-0.034729,0.376702
37,email_duration_3_months_or_less,uint8,other_info,-1,1.000000,True,-0.033669,0.391451
38,bank_account_duration_7_12_months,uint8,personal_finance,-1,1.000000,True,-0.032270,0.411445
39,residence_duration_1_2_years,uint8,other_info,-1,1.000000,True,0.028757,0.464229
40,how_use_money_bills_auto,uint8,personal_finance,-1,1.000000,True,0.027949,0.476875
41,rent_to_income_ratio,float64,personal_finance,0,1.000000,True,-0.026568,0.498931
42,expense_type_housing,uint8,personal_finance,-1,1.000000,True,-0.025325,0.519237
43,how_use_money_school,uint8,personal_finance,-1,1.000000,True,-0.025288,0.519839
44,expense_type_education,uint8,personal_finance,-1,1.000000,True,-0.025288,0.519839
45,how_use_money_rent,uint8,personal_finance,-1,1.000000,True,-0.025288,0.519839
46,expense_type_transportation,uint8,personal_finance,-1,1.000000,True,0.025090,0.523116
47,email_duration_months,float64,other_info,0,1.000000,True,0.017248,0.660712
48,raw_l2c_score,int64,credit_score,0,1.000000,True,0.017142,0.662671
49,bank_id_0005,uint8,personal_finance,-1,1.000000,True,0.016410,0.676235
50,expense_type_medical,uint8,personal_finance,-1,1.000000,True,-0.016085,0.682292
51,monthly_income_amount,int64,personal_finance,0,1.000000,True,-0.014465,0.712799
52,home_phone_type_work,uint8,other_info,-1,1.000000,True,0.014284,0.716242
53,email_duration_1_year_or_more,uint8,other_info,-1,1.000000,True,0.014116,0.719432
54,application_day_of_year,int64,other_info,0,1.000000,True,0.013557,0.730101
55,bank_id_7955,uint8,personal_finance,-1,1.000000,True,0.008873,0.821377
56,residence_duration_6_months_or_less,uint8,other_info,-1,1.000000,True,-0.006305,0.872531
57,how_use_money_bills_home_utilities,uint8,personal_finance,-1,1.000000,True,0.006194,0.874758
58,email_duration_4_12_months,uint8,other_info,-1,1.000000,True,0.006066,0.877334
59,how_use_money_car,uint8,personal_finance,-1,1.000000,True,0.003751,0.923953
60,other_phone_type_home,uint8,other_info,-1,1.000000,True,-0.003088,0.937360
61,how_use_money_bills_medical,uint8,personal_finance,-1,1.000000,True,0.002386,0.951595
62,application_hour_of_day,int64,other_info,0,1.000000,True,0.000076,0.998465
63,customer_id,object,performance,1,1.000000,False,NaN,NaN
64,amount_requested,int64,terms,0,1.000000,False,NaN,NaN
65,birth_date,datetime64[ns],protected,1,1.000000,False,NaN,NaN
66,status,object,terms,1,1.000000,False,NaN,NaN
67,application_when,datetime64[ns],application,1,1.000000,False,NaN,NaN
68,loan_duration,int64,application,0,1.000000,False,NaN,NaN
69,num_payments,int64,terms,0,1.000000,False,NaN,NaN
70,payment_amount,float64,terms,0,1.000000,False,NaN,NaN
71,amount_approved,int64,terms,0,1.000000,False,NaN,NaN
72,duration_approved,int64,terms,0,1.000000,False,NaN,NaN
73,payment_amount_approved,float64,terms,0,0.966154,False,NaN,NaN
74,address_zip,object,protected,1,1.000000,False,NaN,NaN
75,email,object,protected,1,1.000000,False,NaN,NaN
76,bank_routing_number,object,protected,1,1.000000,False,NaN,NaN
77,idLoan,object,performance,1,1.000000,False,NaN,NaN
78,bad,uint8,performance,0,1.000000,False,NaN,NaN

## Export Data

In [8]:
data.to_pickle('output_data/02_data.pkl')
data_dict.to_pickle('output_data/02_data_dict.pkl')